return {
  -- {
  --   "folke/persistence.nvim",
  --   event = "BufReadPre",
  --   opts = {
  --     options = vim.opt.sessionoptions:get(),
  --     pre_save = function()
  --       vim.api.nvim_exec_autocmds("User", { pattern = "SessionSavePre" })
  --     end,
  --   },
  --   keys = {
  --     {
  --       "<leader>qs",
  --       function()
  --         require("persistence").load()
  --       end,
  --       desc = "Restore Session",
  --     },
  --     {
  --       "<leader>ql",
  --       function()
  --         require("persistence").load({ last = true })
  --       end,
  --       desc = "Restore Last Session",
  --     },
  --     {
  --       "<leader>qd",
  --       function()
  --         require("persistence").stop()
  --       end,
  --       desc = "Don't Save Current Session",
  --     },
  --   },
  -- },
}
